# Generated by Django 5.2.15 on 2026-07-07 13:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def assign_owner_to_existing_todos(apps, schema_editor):
    Todo = apps.get_model("todos", "Todo")
    User = apps.get_model(settings.AUTH_USER_MODEL)
    user, _ = User.objects.get_or_create(
        username="admin",
        defaults={"is_staff": True, "is_superuser": True},
    )
    Todo.objects.filter(owner__isnull=True).update(owner=user)


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0002_seed_categories'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='owner',
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='todos',
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.RunPython(assign_owner_to_existing_todos, migrations.RunPython.noop),
    ]
